-- extract_exposure.sql
-- Ported from MONTHLY-EXPOSURE.jcl lines 40-57
-- Aggregates exposure data by LOB, branch, coverage type, territory, and class
-- for actuarial analysis (loss reserving and pricing models).
SELECT P.POLICY_TYPE, P.BRANCH_CODE, C.COVERAGE_TYPE,
       C.RATING_TERRITORY, C.CLASS_CODE,
       COUNT(*) AS POLICY_COUNT,
       SUM(C.COVERAGE_LIMIT) AS TOTAL_EXPOSURE,
       SUM(C.PREMIUM) AS TOTAL_PREMIUM,
       SUM(C.DEDUCTIBLE) AS TOTAL_DEDUCTIBLE
FROM POLICIES P
JOIN COVERAGES C ON P.POLICY_NUMBER = C.POLICY_NUMBER
WHERE P.POLICY_STATUS = 'AC'
  AND C.STATUS = 'AC'
GROUP BY P.POLICY_TYPE, P.BRANCH_CODE,
         C.COVERAGE_TYPE, C.RATING_TERRITORY, C.CLASS_CODE
ORDER BY P.POLICY_TYPE, P.BRANCH_CODE
