-- extract_coverages.sql
-- Ported from DAILY-EXTRACT.jcl lines 75-80
-- Extracts active coverage records for the Claims Engine.
SELECT POLICY_NUMBER, SEQUENCE_NUM, COVERAGE_TYPE,
       DESCRIPTION, COVERAGE_LIMIT, DEDUCTIBLE,
       PREMIUM, EFFECTIVE_DATE, EXPIRY_DATE, STATUS
FROM COVERAGES
WHERE STATUS = 'AC'
ORDER BY POLICY_NUMBER, SEQUENCE_NUM
