-- extract_policies.sql
-- Ported from DAILY-EXTRACT.jcl lines 47-55
-- Extracts recently updated active/pending policies for the Claims Engine.
SELECT POLICY_NUMBER, POLICY_TYPE, POLICY_STATUS,
       EFFECTIVE_DATE, EXPIRY_DATE,
       POLICYHOLDER_ID, AGENT_CODE, BRANCH_CODE,
       TOTAL_PREMIUM, DEDUCTIBLE, COVERAGE_LIMIT,
       UW_STATUS, RISK_SCORE
FROM POLICIES
WHERE POLICY_STATUS IN ('AC', 'PN')
  AND LAST_UPDATED >= CURRENT_DATE - INTERVAL '1 DAY'
ORDER BY POLICY_NUMBER
