-- insert_premium.sql
-- Ported from PREMBAT.cbl lines 202-218
-- Inserts a calculated premium record.
INSERT INTO PREMIUMS
  (POLICY_NUMBER, COVERAGE_SEQ, TERM_EFFECTIVE_DATE, TERM_EXPIRY_DATE,
   BASE_RATE, TERRITORY_FACTOR, CLASS_FACTOR, EXPERIENCE_MOD, SCHEDULE_MOD,
   DISCOUNT_PCT, SURCHARGE_AMT, TAX_AMT, TOTAL_PREMIUM, INSTALLMENT_CODE,
   CALC_DATE, CALC_BY)
VALUES
  (%s, 1, %s, %s, %s, %s, %s, %s, 1.0000, 0.00, %s, %s, %s, 'AN', CURRENT_DATE, 'AIRFLOW')
